name: Build and Publish Plugin
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build Plugin
        run: npm run build
      - name: Publish Plugin
        uses: actions/upload-artifact@v2
        with:
          name: my-plugin
          path: dist/my-plugin.llplugin
