name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare directories
        run: |
          mkdir tmp
          mkdir tmp/sparkbridge
      - name: Copy SparkBridge files
        run: |
          xcopy sparkbridge tmp/sparkbridge /s /e /exclude:%cd%\sparkbridge\buildtool\pack.config
        shell: cmd
      - name: Compress Sparkbridge files
        run: |
          cd tmp/sparkbridge
          7za a ../sparkbridge.zip *
        shell: cmd
      - name: Rename artifact
        run: |
          cd tmp
          ren sparkbridge.zip sparkbridge.llplugin
        shell: cmd
      - name: Upload Action File
        uses: actions/upload-artifact@v2
        with:
          name: sparkbridge
          path: ./tmp/sparkbridge.llplugin
